### PR TITLE
feat: add docs for client url params auto-fill (form, search)

### PR DESCRIPTION
**Pull request by gavriliumircea**
This PR aims to add a separate section for the frontend integrations, namely the create form url params and the search engine url params.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
What other integrations do we expect to nest underneath this new "Integrations" section?

I would prefer to remove the parent "Integrations" category and keep only "URL Schemes" in the sidebar. This way, we could nest the child sections "Stream Page", "Create Stream Form", and "Search Streams" under the left-hand sidebar. They would have better visibility this way.

**Comment by PaulRBerg** [comment]
btw kudos on the URL params feature, looks sick @gavriliumircea

**Comment by razgraf** [comment]
> What other integrations do we expect to nest underneath this new "Integrations" section?

Hmm, was thinking of the SDK.

Arguments for keeping the nesting like this:
- Even now, I wouldn't pollute the left sidebar by listing each separate URL schemes. They have their own content tree on the right side of the `URL Schemes` page.
- By preempting multiple future integrations it makes it so links will stay the same (e.g. `apps/integrations/url-schemes`) when eventually we add a new integration

**Comment by PaulRBerg** [comment]
I performed a thorough review of this new guide, and I'm still in favor of getting rid of the "Integrations" parent nesting on the basis of YAGNI. I can't think of any page that will be added here any time soon.

See my updates in https://github.com/sablier-labs/v2-docs/commit/32b986a98c9fb5543aa031c7635dfb300a8bd460.

> was thinking of the SDK.

That will go under "Contracts", there's already a [draft](https://github.com/sablier-labs/v2-docs/blob/main/docs/contracts/v2/guides/07-frontend.md) prepared for it.

> They have their own content tree on the right side of the URL Schemes page.

yes, and they can be hardly be seen.

> Their titles are longer than the main sections (guides, branding) so alignment will feel weird.

this is such a minor point, isn't it? 😅

It's impossible to keep having the same word length in a table of contents, forever.

> it makes it so links will stay the same ... when eventually we add a new integration.

yes but on the basis of YAGNI we may not need to ever introduce this category

**Comment by PaulRBerg** [comment]
Another point in favor of removing "Integrations": integrations of Sablier need not be front-end only. They are often smart contract-based as it is the case with most NFT ideas we have.

**Comment by razgraf** [comment]
If it's a personal preference sure, let's change it! 

---

Regarding the location of "SDK" and "Integrations" - they will definitely cause some co-location. There will be a Frontend > SDK (UI components) as well as a Contracts > SDK (subgraph, facade for calling methods) regardless of the code being in the same repository or not. Same with integrations. So it's not a one-or-the-other situation.

I agree however, for URL Schemes, given that they're the only item right now and that they're soft "integrations" (but integrations nevertheless, as in ways for external systems to work with our frontend). Therefore, I'm ok with changing the nesting here.

**Comment by PaulRBerg** [comment]
> There will be a Frontend > SDK (UI components) as well as a Contracts > SDK

Fair point - but we can think about the exact location later.

>  they're soft "integrations" (but integrations nevertheless

Are they just integrations? Typical users can use them for non-integration purposes, e.g. accounting.

**Pull request merged**
